source: # source should either be of type file or db
  file:
    type: csv
    path: "p.csv"
    seperator: ;
  db: # chose one between table and sql. Other fields are mandatory
    type: 
    user: 
    pass: 
    host: 
    port: 
    schema: 
    table: 
    sql:  
    
target: # can be a table in database or file type
  file:
    type: xml
    path: "test.xml"
    seperator: 
  db:
    type: 
    user: 
    pass: 
    host: 
    port: 
    schema: 
    table: 